package com.ccanozerr.fr.domain.metadata.enumtypes;

public enum League {
	ENGLISH_PREMIER_LEAGUE,
	SPANISH_LA_LIGA,
	GERMAN_BUNDESLIGA,
	ITALIAN_SERIE_A,
	FRENCH_LEAGUE_1,
	DUTCH_EREDIVISIE,
	PORTUGUESE_PRIMEIRA_LEAGUE,
	TURKISH_SUPER_LEAGUE
}
